apiVersion: skaffold/v2beta29
kind: Config
profiles:
- name: local-microk8s
  build:
    artifacts:
    - image: localhost:32000/kwonghung/springboot3-webflux
      context: springboot3-webflux
      jib:
        type: maven
    insecureRegistries: ["localhost:32000"]
  deploy:
    kubectl:
      manifests: [
        "profiles/microk8s/k8s/ingress-config.yaml",
        "profiles/microk8s/k8s/webflux-*.yaml",
        "profiles/microk8s/k8s/prometheus-*.yaml",
        "profiles/microk8s/k8s/grafana-*.yaml",
        "profiles/microk8s/k8s/pushgateway-*.yaml",
        "profiles/microk8s/k8s/selfsigned-cert.yaml"
      ]