apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  datasrc.yml: |-
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        version: 1
        editable: false

