apiVersion: v1
kind: Service
metadata:
  name: webflux-service
spec:
  type: ClusterIP
  selector:
    app: webflux
  ports:
  - name: netty
    port: 8080
    targetPort: 8080
  - name: pushgateway
    port: 9091
    targetPort: 9091

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webflux-deployment
spec:
  selector:
    matchLabels:
      app: webflux
  replicas: 1
  template:
    metadata:
      labels:
        app: webflux
    spec:
      containers:
      - name: spring-boot
        image: localhost:32000/kwonghung/springboot3-webflux
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8080
        - name: actuator
          containerPort: 8081
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: local-microk8s
        volumeMounts:
          # the path /app/resources is created by jib 
          - mountPath: /app/resources/certs
            name: selfsigned-jks
        
        readinessProbe:
          httpGet:
            port: actuator
            path: /actuator/health/readiness
          initialDelaySeconds: 60
          periodSeconds: 120
          successThreshold: 1
          failureThreshold: 3

        livenessProbe:
          httpGet:
            port: actuator
            path: /actuator/health/liveness
          initialDelaySeconds: 60
          periodSeconds: 120
          successThreshold: 1
          failureThreshold: 3

      volumes:
      - name: selfsigned-jks
        secret:
          secretName: selfsigned-secret
