spring:
  devtools:
    add-properties: false

server:
  http2:
    enabled: true
#  ssl:
#    enabled: true
#    key-store: file:/app/resources/certs/keystore.jks
#    key-store-password: passw0rd
#  servlet:
#    context-path: /webflux

logging:
  level:
    io.prometheus: debug

management:
  endpoints:
    web:
      exposure:
        include: #"*"
        - health
        - metrics
        - prometheus
  endpoint:
    health:
      probes:
        enabled: true
  server:
    port: 8081

---
spring:
  config:
    activate:
      on-profile:
      - local-sts

server:
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:selfsigned.p12
    key-store-type: PKCS12
    key-store-password: abcd1234

---
spring:
  config:
    activate:
      on-profile:
      - local-microk8s
          
management:
  prometheus:
    metrics:
      export:  
        pushgateway:
          enabled: true
          base-url: http://pushgateway-service:9091
          shutdown-operation: push
