{
 "title": "Webflux dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{uri=\"/echo\",outcome!=\"SUCCESS\"}[1m])/increase(http_server_requests_seconds_count{uri=\"/echo\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Threads ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "jvm_threads_states_threads", "legendFormat": "{{state}}" },
    { "expr": "jvm_threads_peak_threads", "legendFormat": "peak" },
    { "expr": "jvm_threads_live_threads", "legendFormat": "live" }
   ]
  },
  {
   "title": "Average Response Time in Last min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expression": "${A}/${B}", "type": "math" }
   ]
  },
  {
   "title": "# of new requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{uri=\"/echo\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}